// ts-basic/views/bottom-bar/index.tsx
import React from 'react'
// @ts-ignore
import { useRelinx, observe, useGlobal, useNamespace } from '../../../src'
import { Styles } from '../../types'

const styles: Styles = {
  wrapper: {
    right: 0,
    bottom: 0,
    left: 0,
    height: 50,
    position: 'absolute',
    backgroundColor: '#fff',
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderTop: '1px solid #eee',
  },
  text: {
    fontSize: 16,
    lineHeight: '20px',
    marginTop: 15,
    paddingLeft: 15,
    color: 'rgb(230, 48, 48)',
    position: 'relative',
    display: 'block',
  },
}

const BottomBar = () => {
  const [state] = useRelinx('bottomBar')
  const value = useGlobal()
  const namespace = useNamespace()

  const [collections, globalDispatch] = useGlobal()
  const group = collections.filter(collection => {
    const { namespace: targetNamespace } = collection
    return targetNamespace === namespace
  })

  globalDispatch([{
    namespace: 'address-list',
    actions: [{
      type: 'addressList/setSelectedId',
      payload: 'x',
    }],
  }])

  const { count } = state

  return (
    <div style={styles.wrapper}>
      <span style={styles.text}>
        {`number ${count}`}
      </span>
    </div>
  )
}

export default observe(BottomBar)

// examples/basic-vue/src/components/BottomBar.vue
<template>
  <div>
    <div class="wrapper">
      <span class="text">
        number {{count}}
      </span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'BottomBar',
  computed:{
    count(){
      return this.$store.state.bottomBar.count;
    }
  }
};
</script>

<style scoped>
.wrapper {
  right: 0;
  bottom: 0;
  left: 0;
  height: 50px;
  position: absolute;
  background-color: #fff;
  border-bottom-right-radius: 20px;
  border-bottom-left-radius: 20px;
  border-top: 1px solid #eee;
}
.text {
  font-size: 16px;
  line-height: 20px;
  margin-top: 15px;
  padding-left: 15px;
  color: rgb(230, 48, 48);
  position: relative;
  display: block;
}
</style>
