// ts-basic/views/goods-view/index.tsx
import React, { CSSProperties, useRef } from 'react'
// @ts-ignore
import { useRelinx, observe } from '../../../src'
import GoodsItem from './GoodsItem'

const GoodsView = () => {
  const [state] = useRelinx('goods')
  const { listData } = state
  const updateCount = useRef(0)

  updateCount.current = updateCount.current + 1
  const spanStyle: CSSProperties = {
    position: 'absolute',
    top: 0,
    left: '20px',
    color: 'red',
  }

  return (
    <div>
      <span style={spanStyle}>
        {`view update ${updateCount.current}`}
      </span>
      {listData.map((data, key) => (
        <GoodsItem
          key={key}
          data={data}
          index={key}
        />
      ))}
    </div>
  )
}

export default observe(GoodsView)

// examples/basic-vue/src/components/GoodsView.vue
<template>
  <div>
    <span class="span-style">view update {{current}}, length {{listLength}}</span>
    <goods-item
      v-for="(item, index) in listData"
      :key="index"
      :id="item.id"
      :index="index"
    ></goods-item>
  </div>
</template>

<script>
import GoodsItem from './GoodsItem';
export default {
  name: 'GoodsView',
  components: {
    GoodsItem,
  },
  data() {
    return {
      current: 0,
    };
  },
  computed: {
    listData() {
      return this.$store.state.goods.listData;
    },
    listLength() {
      return this.$store.state.goods.listLength;
    },
  },
  beforeUpdate() {
    this.current +=1
  },
};
</script>

<style scoped>
.span-style {
  position: absolute;
  top: 0;
  left: 20px;
  color: red;
}
</style>
