// ts-basic/views/load-more/index.tsx
import React, { useCallback } from 'react'
// @ts-ignore
import { observe, useDispatch } from '../../../src'
import { Styles } from '../../types'

const styles: Styles = {
  wrapper: {
    width: '100%',
    height: 50,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: '50px',
    backgroundColor: '#5cbd3c',
  },
}

const LoadMore = () => {
  const [dispatch] = useDispatch()
  const handleClick = useCallback(() => {
    dispatch({
      type: 'init/getGoodsList',
    })
  }, [])

  return (
    <div style={styles.wrapper} onClick={handleClick}>
      获取更多
    </div>
  )
}

export default observe(LoadMore)

// examples/basic-vue/src/components/LoadMore.vue
<template>
  <div
    class="wrapper"
    @click="handleClick"
  >
    获取更多
  </div>
</template>

<script>
export default {
  name: 'LoadMore',
  methods:{
    handleClick(){
      this.$store.dispatch('init/getGoodsList')
    }
  }
};
</script>

<style scoped>
.wrapper {
  width: 100%;
  height: 50px;
  text-align: center;
  font-size: 16px;
  line-height: 50px;
  background-color: #5cbd3c;
}
</style>
